# =======================================================
# GAO Schedule Auditor - Streamlit UI Configuration
# =======================================================

[theme]
base="light"
primaryColor="#0033A0"                # Deep GAO blue
backgroundColor="#FFFFFF"             # White main background
secondaryBackgroundColor="#F5F6FA"    # Subtle gray panels
textColor="#1E1E1E"                   # Clean dark text
font="sans serif"

[ui]
layout="wide"                         # Full-width layout for dashboards
hideTopBar=false
showErrorDetails=true

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
port=8501

[client]
toolbarMode="minimal"
showErrorDetails=true

[browser]
gatherUsageStats=false
serverAddress="localhost"

# =======================================================
# Optional Branding Section
# =======================================================
[custom]
appTitle="GAO Schedule Quality Auditor"
appSubtitle="Automated Schedule Assessment & Dependency Analysis"
appFavicon="https://upload.wikimedia.org/wikipedia/commons/2/25/GAO_logo_2021.svg"
appLogo="https://upload.wikimedia.org/wikipedia/commons/2/25/GAO_logo_2021.svg"

