[theme]
primaryColor = "#004578"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f9fb"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
